CREATE TABLE TBL_DETAIL_FUND (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    FUND_CODE           VARCHAR2(50)       NOT NULL,
    BID_PRICE           NUMBER(20),
    OFFER_PRICE         NUMBER(20),
    PRICE_ENTRY_DATE    TIMESTAMP(6),
    PRICE_EFFECTIVE_DATE TIMESTAMP(6),
    FUND_STATUS         VARCHAR2(20),
    APPROVED_DATE       TIMESTAMP(6),
    PRICE_STATUS        VARCHAR2(20),
    LAST_APPROVED_BY    VARCHAR2(100),
    LAST_ENTERED_BY     VARCHAR2(100)
);

CREATE UNIQUE INDEX TBL_DETAIL_FUND_PK ON TBL_DETAIL_FUND (ID);

ALTER TABLE TBL_DETAIL_FUND ADD (
  CONSTRAINT TBL_DETAIL_FUND_PK
  PRIMARY KEY
  (ID)
  USING INDEX TBL_DETAIL_FUND_PK
  ENABLE VALIDATE);
  
//=========================================
  
CREATE TABLE TBL_MASTER_FUND (
    CODE VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(200),
    CONSTRAINT PK_MASTER_FUND PRIMARY KEY (CODE)
);

//========================================

CREATE TABLE TBL_TOKEN_STORE (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
    SESSION_NAME        VARCHAR2(50)       NOT NULL,
    TOKEN_VALUE           VARCHAR2(4000),
    EXPIRY_DATE         TIMESTAMP(6)
);

CREATE UNIQUE INDEX TBL_TOKEN_STORE_PK ON TBL_TOKEN_STORE (ID);

ALTER TABLE TBL_TOKEN_STORE ADD (
  CONSTRAINT TBL_TOKEN_STORE_PK
  PRIMARY KEY
  (ID)
  USING INDEX TBL_TOKEN_STORE_PK
  ENABLE VALIDATE);