DROP TABLE MYAPP.FILE_DOK_METADATA CASCADE CONSTRAINTS;

CREATE TABLE MYAPP.FILE_DOK_METADATA
(
  ID               NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  FILE_NAME        VARCHAR2(200 BYTE),
  FILE_CATEGORY    VARCHAR2(50 BYTE),
  DOCUMENT_CODE    VARCHAR2(50 BYTE),
  CONTENT_BASE64   CLOB,
  FILE_SIZE        NUMBER,
  FILE_DATE    TIMESTAMP(6),
  PATH_DIRECTORY   VARCHAR2(500 BYTE),
  STORAGE_TYPE     VARCHAR2(20 BYTE),
  DOCUMENT_TYPE    VARCHAR2(50 BYTE),
  NASABAH_ID       VARCHAR2(50 BYTE),
  POLICY_ID        VARCHAR2(50 BYTE),
  ENCRYPTED_FLAG   CHAR(1 BYTE),
  ACCESS_LEVEL     VARCHAR2(20 BYTE),
  CREATED_BY       VARCHAR2(50 BYTE),
  REGISTER_DATE    TIMESTAMP(6)
)
LOB (CONTENT_BASE64) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX MYAPP.FILE_DOK_METADATA_PK ON MYAPP.FILE_DOK_METADATA
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MYAPP.FILE_DOK_METADATA ADD (
  CONSTRAINT FILE_DOK_METADATA_PK
  PRIMARY KEY
  (ID)
  USING INDEX MYAPP.FILE_DOK_METADATA_PK
  ENABLE VALIDATE);


--DROP SEQUENCE MYAPP.ISEQ$$_76119;

-- Sequence ISEQ$$_76119 is created automatically by Oracle for use with an Identity column
